spring:
  data:
    neo4j:
      username: neo4j
      password: admin
      uri: bolt://localhost:7687
      auto-index: update

logging:
  level:
    root: info
    org.neo4j.ogm.drivers.bolt.request.BoltRequest: info
    org.neo4j.ogm.session.delegates: debug
